companies/urls.py
from django.urls import path
from companies import views


app_name = 'companies'
urlpatterns = [
    path('', views.CompaniesList.as_view(), name='list'),
    path('<int:pk>/', views.CompanyDetails.as_view(), name='details'),
    path('add/', views.CompanyAdd.as_view(), name='add'),
    path('<int:pk>/update/', views.CompanyUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', views.CompanyDelete.as_view(), name='delete'),
    path('reviews/add/', views.CompanyReviewAdd.as_view(), name='review-add'),
    path('reviews/<int:pk>/update/', views.CompanyReviewUpdate.as_view(), name='review-update'),
    path('review/<int:pk>/delete/', views.CompanyReviewDelete.as_view(), name='review-delete'),
]

forum/urls.py
from django.urls import path
from forum import views


app_name = 'forum'
urlpatterns = [
    path('', views.CategoriesList.as_view(), name='list'),
    path('<int:pk>/', views.CategoryDetails.as_view(), name='details'),
    path('threads/add/', views.ThreadAdd.as_view(), name='thread-add'),
    path('threads/<int:pk>/', views.ThreadDetails.as_view(), name='thread-details'),
    path('messages/add/', views.MessageAdd.as_view(), name='message-add'),
]

companies/models.py
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models


class CompanyManager(models.Manager):
    ''' '''

    def get_for_user_houses(self, user):
        ''' '''
        if user.is_authenticated:
            return self.filter(city__in=user.get_cities()).order_by('title')
        return tuple()


class Company(models.Model):
    ''' '''

    title = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    phone = models.CharField(max_length=15)
    href = models.URLField(max_length=255, blank=True, null=True)
    email = models.EmailField(max_length=255, blank=True, null=True)
    rate = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    rated = models.PositiveSmallIntegerField(blank=True, null=True)
    city = models.ForeignKey('houses.City', models.CASCADE)

    objects = CompanyManager()

    def __str__(self) -> str:
        ''' '''
        return self.title

    def has_admin_access(self, user) -> bool:
        ''' '''
        if user.is_authenticated:
            return user.has_any_house_admin_access(self.houses.all())
        return False


class CompanyReviewManager(models.Manager):
    ''' '''

    def get_for_company(self, company: Company):
        ''' '''
        return self.filter(company=company).order_by('-updated_dt')

    def get_rate(self, company: Company):
        ''' '''
        res = self.filter(company=company).aggregate(models.Count('id', distinct=True), models.Avg('rate'))
        return float(res['rate__avg']), res['id__count'] if res['rate__avg'] else 0, 0


class CompanyReview(models.Model):
    ''' '''

    rate = models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    message = models.TextField(blank=True, null=True)
    updated_dt = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, models.CASCADE)
    company = models.ForeignKey(Company, models.CASCADE, related_name='reviews')

    objects = CompanyReviewManager()

    def __str__(self) -> str:
        ''' '''
        return f'Review {self.id} for company #{self.company_id}'

companies/forms.py
from django.forms import ModelForm
from utils.forms import FormMixin
from companies import models


class CompanyForm(FormMixin, ModelForm):
    ''' '''

    class Meta:
        model = models.Company
        fields = ['title', 'address', 'href', 'city', 'phone', 'email']

    def __init__(self, cities, *args, **kwargs):
        ''' '''
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = cities

companies/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from companies import models, forms
from houses.models import City
from utils import views as uviews


class CompaniesList(ListView):
    ''' '''

    context_object_name = 'companies'
    model = models.Company
    template_name = 'companies/list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        ''' '''
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['user_companies'] = self.request.user.get_companies() if self.request.user.is_authenticated else []
        return context


class CompanyDetails(DetailView):
    ''' '''

    model = models.Company
    context_object_name = 'company'
    template_name = 'companies/details.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        ''' '''
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['reviews'] = models.CompanyReview.objects.get_for_company(context[self.context_object_name])
        context['user_review'] = context['reviews'].filter(user=self.request.user).first()
        return context


class CompanySaveMixin():
    ''' '''

    model = models.Company
    template_name = 'companies/form.html'
    form_class = forms.CompanyForm

    def get_form_kwargs(self):
        ''' '''
        kwargs = super().get_form_kwargs()
        kwargs.update({'cities': City.objects.get_for_user(self.request.user)})
        return kwargs

    def get_success_url(self):
        ''' '''
        return reverse('companies:details', args=(self.object.id,))


class CompanyAdd(uviews.HouseAdminCreateMixin, CompanySaveMixin, CreateView):
    ''' '''


class CompanyUpdate(uviews.HouseAdminManageMixin, CompanySaveMixin, UpdateView):
    ''' '''


@method_decorator(require_POST, name='dispatch')
class CompanyDelete(uviews.HouseAdminManageMixin, DeleteView):
    ''' '''

    model = models.Company
    success_url = reverse_lazy('companies:list')


class CompanyReviewSuccessMixin():
    ''' '''

    def get_success_url(self):
        ''' '''
        return reverse('companies:details', args=(self.object.company_id,))


class CompanyReviewSaveMixin(CompanyReviewSuccessMixin):
    ''' '''

    model = models.CompanyReview
    fields = ['rate', 'message', 'company']


@method_decorator(require_POST, name='dispatch')
class CompanyReviewAdd(uviews.AddUserMixin, CompanyReviewSaveMixin, CreateView):
    ''' '''


@method_decorator(require_POST, name='dispatch')
class CompanyReviewUpdate(uviews.IsOwnerMixin, CompanyReviewSaveMixin, UpdateView):
    ''' '''


@method_decorator(require_POST, name='dispatch')
class CompanyReviewDelete(uviews.IsOwnerMixin, CompanyReviewSuccessMixin, DeleteView):
    ''' '''

    model = models.CompanyReview

companies/templates/companies/details.html
{% extends "base.html" %}
{% load custom %}

{% block title %}{{ block.super }} Упр. компании{% endblock title %}

{% block content %}

<div class="row">
  <div class="col"><h2>{{ company.title }}</h2></div>
  {% if company|object_can_admin:user %}
    {% url 'companies:update' company.id as update_url %}
    {% url 'companies:delete' company.id as delete_url %}
    {% include "utils/actions.html" with update_url=update_url delete_url=delete_url %}
  {% endif %}
</div>
<div class="row">
  <div class="col"><b>Оценка/Отзывов:</b> {{ company.rate|default_if_none:0 }}/{{ company.rated|default_if_none:0 }}</div>
</div>
<div class="row">
  <div class="col"><b>Адрес:</b> {{ company.address }}</div>
</div>
<div class="row">
  <div class="col"><b>Телефон:</b> {{ company.phone }}</div>
</div>
{% if company.email %}
  <div class="row">
    <div class="col"><b>Эл. почта:</b> <a href="mailto:{{ company.email }}" target="_blank">{{ company.email }}</a></div>
  </div>
{% endif %}
{% if company.href %}
  <div class="row">
    <div class="col"><a href="{{ company.href }}" target="_blank">Сайт</a></div>
  </div>
{% endif %}

{% if user.is_authenticated %}
<div class="row mt-3">
  <div class="col-sm-2">
    <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapse" role="button" aria-expanded="false" aria-controls="collapseExample">
      Оставить отзыв
    </a>
  </div>
</div>
<div class="collapse row border mt-1" id="collapse">
  <div class="col">
    <form method="POST" action="{% if user_review %}{% url 'companies:review-update' user_review.id %}{% else %}{% url 'companies:review-add' %}{% endif %}">
      {% csrf_token %}
      <input type="hidden" name="company" value="{{ company.id }}">
      <div class="row">
        <div class="col pt-3">
          <label for="rate" class="form-label">Оценка:</label>
          {% for val in '12345'|make_list %}
            <div class="form-check form-check-inline">
              <input class="form-check-input" type="radio" name="rate" id="rate{{ val }}" value="{{ val }}" {% if user_review.rate|stringformat:'1d' == val %}checked=""{% endif %}>
              <label class="form-check-label" for="rate{{ val }}">{{ val }}</label>
            </div>
          {% endfor %}
        </div>
      </div>
      <div class="row">
        <div class="col">
          <label for="message" class="form-label">Отзыв</label>
          <textarea id="message" name="message" class="form-control" rows="5">{% if user_review %}{{ user_review.message|default_if_none:'' }}{% endif %}</textarea>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-2 mt-1 ms-auto">
          <button class="w-100 btn btn-primary btn-lg" type="submit">Сохранить</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endif %}

{% if reviews %}
<div class="row mt-5">
  <div class="col">
    <h3>Отзывы</h3>
    {% for review in reviews %}
      <div class="card">
        <div class="card-body">
          <div class="card-title">
            Отзыв от: <b>{{ review.user.title }}</b>, оценка: <b>{{ review.rate }}</b>, {{ review.updated_dt|change_tz:user|date:'d.m.Y H:i:s' }}
          </div>
          <p class="card-text">{{ review.message }}</p>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
{% endif %}

{% endblock content %}

companies/templates/companies/form.html
{% extends "base.html" %}

{% block title %}{{ block.super }} Упр. компании{% endblock title %}

{% block content %}

<div class="col-lg-6">

  <form method="POST" class="needs-validation" novalidate>
    {% csrf_token %}
    <div class="row g-3">

      <div class="col-12">
        <label for="title" class="form-label">Название</label>
        <input type="text" id="title" name="title" class="form-control {% if form.is_bound %}is-{% if form.title.errors %}in{% endif %}valid{% endif %}" required autofocus value="{{ form.title.value|default_if_none:'' }}">
        <div class="invalid-feedback">{{ form.title.errors }}</div>
      </div>

      <div class="col-12">
        <label for="address" class="form-label">Адрес</label>
        <input type="text" id="address" name="address" class="form-control {% if form.is_bound %}is-{% if form.address.errors %}in{% endif %}valid{% endif %}" required value="{{ form.address.value|default_if_none:'' }}">
        <div class="invalid-feedback">{{ form.address.errors }}</div>
      </div>

      <div class="col-12">
        <label for="phone" class="form-label">Телефон</label>
        <input type="text" id="phone" name="phone" class="form-control {% if form.is_bound %}is-{% if form.phone.errors %}in{% endif %}valid{% endif %}" required value="{{ form.phone.value|default_if_none:'' }}">
        <div class="invalid-feedback">{{ form.phone.errors }}</div>
      </div>

      <div class="col-12">
        <label for="href" class="form-label">Сайт</label>
        <input type="url" id="href" name="href" class="form-control  {% if form.is_bound %}is-{% if form.href.errors %}in{% endif %}valid{% endif %}" value="{{ form.href.value|default_if_none:'' }}">
        <div class="invalid-feedback">{{ form.href.errors }}</div>
      </div>

      <div class="col-12">
        <label for="email" class="form-label">Эл. почта</label>
        <input type="text" id="email" name="email" class="form-control {% if form.is_bound %}is-{% if form.email.errors %}in{% endif %}valid{% endif %}" value="{{ form.email.value|default_if_none:'' }}">
        <div class="invalid-feedback">{{ form.email.errors }}</div>
      </div>

      <div class="col-12">
        <label for="city" class="form-label">Город</label>
        <select id="city" class="form-select" name="city" required>
          {% if form.city|length == 2 %}
            {{ form.city.1 }}
          {% else %}
            {% for option in form.city %}
              {{ option }}
            {% endfor %}
          {% endif %}
        </select>
        <div class="invalid-feedback">{{ form.city.errors }}</div>
      </div>

      <hr class="my-4"/>

      <div class="col-12">
        <button class="w-100 btn btn-primary btn-lg" type="submit">Сохранить</button>
      </div>

    </div>
  </form>
</div>

{% endblock content %}

companies/templates/companies/list-item.html
<div class="card mb-3">
  <div class="card-body">
    <div class="card-title">
      <div class="row">
        <div class="col-md-5">
          {{ company.title }}
          {% if company in user_companies %}&nbsp;<b>Ваша УК!</b>{% endif %}
        </div>
        {% if can_admin %}
          {% url 'companies:update' company.id as update_url %}
          {% url 'companies:delete' company.id as delete_url %}
          {% include "utils/actions.html" with update_url=update_url delete_url=delete_url %}
        {% endif %}
      </div>
    </div>
    <p class="card-text">Оценка/Отзывов: {{ company.rate|default_if_none:0 }}/{{ company.rated|default_if_none:0 }}</p>
    <a href="{% url 'companies:details' company.id %}">Подробнее</a>
  </div>
</div>

companies/templates/companies/list.html
{% extends "base.html" %}
{% load custom %}

{% block title %}{{ block.super }} Упр. компании{% endblock title %}

{% block content %}

  {% regroup companies by city as groupped_comps %}

  {% if groupped_comps|length > 1 %}
	<ul class="nav nav-tabs" role="tablist" id="tabsNav">
	  {% for comp in groupped_comps %}
	    <li class="nav-item">
	      <a class="nav-link {% if forloop.counter0 == 0 %}active{% endif %}" id="tab-{{ comp.grouper.id }}" aria-current="page" href="#">{{ comp.grouper.title }}</a>
	    </li>
	  {% endfor %}
	</ul>
	<div class="tab-content" id="companiesTabs">
	  {% for comp in groupped_comps %}
	    <div class="tab-pane fade show {% if forloop.counter0 == 0 %}active{% endif %}" id="{{ comp.grouper.id }}" role="tabpanel" aria-labelledby="tab-{{ comp.grouper.id }}">
	      {% for company in comp.list %}
	        {% include 'companies/list-item.html' with company=company user_companies=user_companies can_admin=company|object_can_admin:user %}
          {% endfor %}
	    </div>
	  {% endfor %}
	</div>
  {% else %}
    {% for company in companies %}
      {% include 'companies/list-item.html' with company=company user_companies=user_companies can_admin=company|object_can_admin:user %}
    {% endfor %}
  {% endif %}

{% endblock content %}