companies/urls.py
from django.urls import path
from companies import views


app_name = 'companies'
urlpatterns = [
    path('', views.CompaniesList.as_view(), name='list'),
    path('<int:pk>/', views.CompanyDetails.as_view(), name='details'),
    path('add/', views.CompanyAdd.as_view(), name='add'),
    path('<int:pk>/update/', views.CompanyUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', views.CompanyDelete.as_view(), name='delete'),
    path('reviews/add/', views.CompanyReviewAdd.as_view(), name='review-add'),
    path('reviews/<int:pk>/update/', views.CompanyReviewUpdate.as_view(), name='review-update'),
    path('review/<int:pk>/delete/', views.CompanyReviewDelete.as_view(), name='review-delete'),
]

forum/urls.py
from django.urls import path
from forum import views


app_name = 'forum'
urlpatterns = [
    path('', views.CategoriesList.as_view(), name='list'),
    path('<int:pk>/', views.CategoryDetails.as_view(), name='details'),
    path('threads/add/', views.ThreadAdd.as_view(), name='thread-add'),
    path('threads/<int:pk>/', views.ThreadDetails.as_view(), name='thread-details'),
    path('messages/add/', views.MessageAdd.as_view(), name='message-add'),
]

houses/urls.py
from django.urls import path
from houses import views


app_name = 'houses'
urlpatterns = [
    path('', views.HousesList.as_view(), name='list'),
    path('<int:pk>/update-info/', views.HouseInfoUpdate.as_view(), name='update-info'),
    path('unlink/<int:pk>/', views.UnlinkUser.as_view(), name='user-unlink'),
    path('link/', views.link_user, name='user-link'),
]

houses/models.py
from django.db import models
from django.conf import settings
from timezone_field import TimeZoneField


class Region(models.Model):
    ''' '''
    
    title = models.CharField(max_length=255, unique=True)
    forum_title = models.CharField(max_length=255)

    def __str__(self) -> str:
        ''' '''
        return self.title


class CityManager(models.Manager):
    ''' '''

    def get_for_user(self, user):
        ''' '''
        if user.is_authenticated and user.has_house():
            return self.filter(houses__users=user)
        return self.all()

    def get_for_weather(self):
        ''' '''
        return self.filter(weather_url__isnull=False)


class City(models.Model):
    ''' '''
    
    title = models.CharField(max_length=100)
    forum_title = models.CharField(max_length=255)
    timezone = TimeZoneField(choices_display='WITH_GMT_OFFSET')
    weather_url = models.URLField(blank=True, null=True)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)

    objects = CityManager()

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['title', 'region'], name='city_in_region')
        ]

    def __str__(self) -> str:
        ''' '''
        return self.title


class HouseManager(models.Manager):
    ''' '''

    def get_for_admin_user(self, user):
        ''' '''
        if not user.is_authenticated:
            return tuple()
        return self.filter(memberships__is_admin=True,memberships__user=user)

    def get_for_user(self, user):
        ''' '''
        if not user.is_authenticated:
            return tuple()
        return self.filter(memberships__user=user)

    def get_for_registration(self, link):
        ''' '''
        return self.filter(reg_link=link).first()


class House(models.Model):
    ''' '''

    title = models.CharField(max_length=255)
    forum_title = models.CharField(max_length=255)
    logo = models.ImageField(blank=True, null=True)
    reg_link = models.CharField(max_length=19, unique=True)
    off_link = models.URLField(blank=True, null=True)
    city = models.ForeignKey(City, on_delete=models.CASCADE, related_name='houses')
    users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='houses', through='HouseMembership')
    company = models.ForeignKey('companies.Company', on_delete=models.SET_NULL, blank=True, null=True, related_name='houses')

    objects = HouseManager()

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['title', 'city'], name='house_in_city')
        ]

    def __str__(self) -> str:
        ''' '''
        return f'{self.city.title} {self.title}'

    def has_admin_access(self, user) -> bool:
        ''' '''
        if not user.is_authenticated:
            return False
        return user.has_house_admin_access(self)

    def list_users(self):
        ''' '''
        return self.users.all().order_by('username')


class HouseMembership(models.Model):
    ''' '''

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='memberships')
    house = models.ForeignKey(House, on_delete=models.CASCADE, related_name='memberships')
    is_admin = models.BooleanField(default=False)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'house'], name='user_in_house')
        ]

    def __str__(self) -> str:
        ''' '''
        return f'Membership {self.user} in {self.house}'

    def has_admin_access(self, user) -> bool:
        ''' '''
        if not user.is_authenticated:
            return False
        return user.has_house_admin_access(self.house)


class RegionInfo(models.Model):
    ''' '''

    info = models.TextField()
    region = models.OneToOneField(Region, on_delete=models.CASCADE, related_name='info')

    def __str__(self) -> str:
        ''' '''
        return f'Info for {self.region.title}'


class CityInfo(models.Model):
    ''' '''

    info = models.TextField()
    city = models.OneToOneField(City, on_delete=models.CASCADE, related_name='info')

    def __str__(self) -> str:
        ''' '''
        return f'Info for {self.city.title}'


class HouseInfo(models.Model):
    ''' '''

    info = models.TextField()
    house = models.OneToOneField(House, on_delete=models.CASCADE, related_name='info')

    def __str__(self) -> str:
        ''' '''
        return f'Info for {self.house.title}'

houses/views.py
from django.views.generic import ListView
from django.views.generic.edit import UpdateView, DeleteView
from django.views.decorators.http import require_POST
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from houses import models
from companies.models import Company
from utils import views as uviews
from users.models import User
from django.shortcuts import redirect


USER_LINK_ERROR_SESSION_KEY = 'user_link_erorr'


class HousesList(uviews.HasHouseMixin, ListView):
    ''' '''

    context_object_name = 'houses'
    model = models.House
    template_name = 'houses/list.html'

    def get_queryset(self):
        ''' '''
        return self.model.objects.get_for_user(self.request.user)

    def get_context_data(self, *, object_list=None, **kwargs):
        ''' '''
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['companies'] = Company.objects.get_for_user_houses(self.request.user)
        if USER_LINK_ERROR_SESSION_KEY in self.request.session:
            context[USER_LINK_ERROR_SESSION_KEY] = self.request.session[USER_LINK_ERROR_SESSION_KEY]
            del self.request.session[USER_LINK_ERROR_SESSION_KEY]
        return context


class HouseSuccessUrlMixin():
    ''' '''
    
    success_url = reverse_lazy('houses:list')


@method_decorator(require_POST, name='dispatch')
class HouseInfoUpdate(HouseSuccessUrlMixin, uviews.HouseAdminManageMixin, UpdateView):
    ''' '''

    model = models.HouseInfo
    fields = ('info',)


@require_POST
@login_required
def link_user(request):
    ''' '''
    house_id = request.POST.get('house_id')
    username = request.POST.get('username')
    is_admin = request.POST.get('is_admin', False)
    if house_id and username:
        house = models.House.objects.filter(id=house_id).first()
        if house:
            if house.has_admin_access(request.user):
                user = User.objects.get_by_username(username)
                if user:
                    membership = models.HouseMembership(user=user, house=house, is_admin=is_admin)
                    membership.save()
                else:
                    request.session[USER_LINK_ERROR_SESSION_KEY] = 'Пользователь не найден'
            else:
                request.session[USER_LINK_ERROR_SESSION_KEY] = 'Нет прав на добавление пользователя'
        else:
            request.session[USER_LINK_ERROR_SESSION_KEY] = 'Дом не найден'
    else:
        request.session[USER_LINK_ERROR_SESSION_KEY] = 'Укажите дом и пользователя'

    return redirect('houses:list')


@method_decorator(require_POST, name='dispatch')
class UnlinkUser(HouseSuccessUrlMixin, uviews.HouseAdminManageMixin, DeleteView):
    ''' '''

    model = models.HouseMembership

houses/templates/houses/list-item.html
{% load custom %}

{% if title %}
  <div class="row"><h2>{{ house.title }}</h2></div>
{% endif %}

{% if house|object_can_admin:user %}
<div class="row mt-3">
  <div class="col">
    <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapse1" role="button" aria-expanded="false" aria-controls="collapse1">
      Изменить
    </a>
    <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapse2" role="button" aria-expanded="false" aria-controls="collapse2">
      Жители
    </a>
    {% if companies|length > 1 or companies.0 != house.company %}
      <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapse3" role="button" aria-expanded="false" aria-controls="collapse3">
        Сменить УК
      </a>
    {% endif %}
  </div>
</div>
<div class="collapse row border mt-1 p-1" id="collapse1">
  <div class="col">
    <form method="POST" action="{% url 'houses:update-info' house.info.id %}">
      {% csrf_token %}
      <div class="row">
        <div class="col">
          <label for="info" class="form-label">Информация</label>
          <textarea id="info" name="info" class="form-control" rows="5">{{ house.info.info|default_if_none:'' }}</textarea>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-2 mt-1 ms-auto">
          <button class="w-100 btn btn-primary btn-lg" type="submit">Сохранить</button>
        </div>
      </div>
    </form>
  </div>
</div>

<div class="collapse row border mt-1 p-1" id="collapse2">
  <div class="col">
    <div class="row">
      <div class="col">
        <form class="row row-cols-lg-auto g-3 align-items-center" method="POST" action="{% url 'houses:user-link' %}">
          <label class="col-form-label col-sm-2" for="username">Добавить жителя</label>
          <div class="col-12">
              <input type="text" class="form-control" id="username" name="username" placeholder="Имя пользователя" required>
          </div>
          <div class="col-12">
            <div class="form-check">
              <input class="form-check-input" type="checkbox" id="is_admin" name="is_admin">
              <label class="form-check-label" for="is_admin">Админ дома</label>
            </div>
          </div>
          <div class="col-12">
            <button type="submit" class="btn btn-primary">Сохранить</button>
          </div>
        </form>
      </div>
    </div>
    <br/>
    <div class="row">
      <div class="col">
        {% for user in house.list_users %}
          {% cycle '<div class="row">' '' %}      
            <div class="col-md-5 me-5">
              <div class="row">
                <div class="col">{{ user.username }}</div>
                {% with user|get_membership:house as mem %}
                  {% if mem %}
                    {% url 'houses:user-unlink' mem.id  as url %}
                    {% include 'utils/actions.html' with update_url=None delete_url=url %}
                  {% endif %}
                {% endwith %}
              </div>
            </div>
          {% cycle '' '</div>' %}
        {% endfor %}
        {% if not house.users.all|length|divisibleby:'2' %}
          </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>

  {% if companies|length > 1 or companies.0 != house.company %}
    <div class="collapse row border mt-1 p-1" id="collapse3">
      <div class="col">
        <form method="POST" action="{% url 'houses:update-info' house.info.id %}">
          {% csrf_token %}
          <div class="row">
            <div class="col">
              <label for="company" class="form-label">УК</label>
              <select name="company" id="company">
                {% for company in companies %}
                  <option value="{{ company.id }}">{{ company.title }}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-2 mt-1 ms-auto">
              <button class="w-100 btn btn-primary btn-lg" type="submit">Сохранить</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  {% endif %}

{% endif %}

{% if house.company %}
  <div class="row mt-3">
    <div class="col">Ваша УК: <a href="{% url 'companies:details' house.company_id %}">{{ house.company }}</a></div>
  </div>
{% endif %}


{% if house.info %}
  <div class="row mt-3">
    <div class="col">{{ house.info.info|safe }}</div>
  </div>
{% endif %}

{% if house.city.info %}
  <div class="row mt-3">
    <div class="col">{{ house.city.info.info|safe }}</div>
  </div>
{% endif %}

{% if house.city.region.info %}
  <div class="row mt-3">
    <div class="col">{{ house.city.region.info.info|safe }}</div>
  </div>
{% endif %}

houses/templates/houses/list.html
{% extends "base.html" %}

{% block title %}{{ block.super }} Информация{% endblock title %}

{% block content %}

  {% if houses|length > 1 %}
	<ul class="nav nav-tabs" role="tablist" id="tabsNav">
	  {% for house in houses %}
	    <li class="nav-item">
	      <a class="nav-link {% if forloop.counter0 == 0 %}active{% endif %}" id="tab-{{ house.id }}" aria-current="page" href="#">{{ house.title }}</a>
	    </li>
	  {% endfor %}
	</ul>
	<div class="tab-content" id="housesTabs">
	  {% for house in houses %}
	    <div class="tab-pane fade show {% if forloop.counter0 == 0 %}active{% endif %}" id="{{ house.id }}" role="tabpanel" aria-labelledby="tab-{{ house.id }}">
	      {% for house in houses %}
            {% include 'houses/list-item.html' with house=house title=0 %}
          {% endfor %}
	    </div>
	  {% endfor %}
	</div>
  {% else %}
    {% for house in houses %}
      {% include 'houses/list-item.html' with house=house title=1 %}
    {% endfor %}
  {% endif %}

{% endblock content %}