forum/urls.py
from django.urls import path
from forum import views


app_name = 'forum'
urlpatterns = [
    path('', views.CategoriesList.as_view(), name='list'),
    path('<int:pk>/', views.CategoryDetails.as_view(), name='details'),
    path('threads/add/', views.ThreadAdd.as_view(), name='thread-add'),
    path('threads/<int:pk>/', views.ThreadDetails.as_view(), name='thread-details'),
    path('messages/add/', views.MessageAdd.as_view(), name='message-add'),
]

tasks/urls.py
from django.urls import path
from tasks import views


app_name = 'tasks'
urlpatterns = [
    path('', views.TasksList.as_view(), name='list'),
    path('<int:pk>/', views.TaskDetails.as_view(), name='details'),
    path('add/', views.TaskAdd.as_view(), name='add'),
    path('<int:pk>/update/', views.TaskUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', views.TaskDelete.as_view(), name='delete'),
    path('rate/add/', views.TaskRateAdd.as_view(), name='rate-add'),
    path('rate/<int:pk>/update/', views.TaskRateUpdate.as_view(), name='rate-update'),
    path('message/add/', views.TaskMessageAdd.as_view(), name='message-add'),
]

tasks/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings


class TaskManager(models.Manager):
    ''' '''

    def get_for_user(self, user):
        ''' '''
        if user.is_authenticated:
            return self.filter(house__users=user).order_by('-rate')
        else:
            return tuple() 

    def get_most_important_for_user(self, user):
        ''' '''
        res = self.get_for_user(user)
        return res if type(res) == tuple else res[:5] 


class Task(models.Model):
    ''' '''

    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    created_dt = models.DateTimeField(auto_now_add=True)
    updated_dt = models.DateTimeField(auto_now=True)
    rate = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    rated = models.PositiveSmallIntegerField(blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, models.CASCADE)
    house = models.ForeignKey('houses.House', models.CASCADE)

    objects = TaskManager()

    def __str__(self) -> str:
        ''' '''
        return self.title

    def has_access(self, user) -> bool:
        ''' '''
        if not user.is_authenticated:
            return False
        return user.has_house_access(self.house)


class TaskRateManager(models.Manager):
    ''' '''

    def get_rate(self, task: Task):
        ''' '''
        res = self.filter(task=task).aggregate(models.Count('id', distinct=True), models.Avg('rate'))
        return float(res['rate__avg']), res['id__count'] if res['rate__avg'] else 0, 0


class TaskRate(models.Model):
    ''' '''

    rate = models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    updated_dt = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, models.CASCADE)
    task = models.ForeignKey(Task, models.CASCADE, related_name='rates')

    objects = TaskRateManager()

    def __str__(self) -> str:
        ''' '''
        return f'Rate {self.id} for task #{self.task_id}'


class TaskMessage(models.Model):
    ''' '''

    message = models.TextField()
    created_dt = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, models.CASCADE)
    task = models.ForeignKey(Task, models.CASCADE, related_name='messages')

    def __str__(self) -> str:
        ''' '''
        return f'Message {self.id} for task #{self.task_id}'

tasks/forms.py
from django.forms import ModelForm
from utils.forms import FormMixin
from tasks import models


class TaskForm(FormMixin, ModelForm):
    ''' '''

    class Meta:
        model = models.Task
        fields = ['title', 'description', 'house']

    def __init__(self, houses, *args, **kwargs):
        ''' '''
        super().__init__(*args, **kwargs)
        self.fields['house'].queryset = houses


class TaskRateForm(FormMixin, ModelForm):
    ''' '''

    class Meta:
        model = models.TaskRate
        fields = ['rate', 'task']

    def __init__(self, tasks, *args, **kwargs):
        ''' '''
        super().__init__(*args, **kwargs)
        self.fields['task'].queryset = tasks


class TaskMessageForm(FormMixin, ModelForm):
    ''' '''

    class Meta:
        model = models.TaskMessage
        fields = ['message', 'task']

    def __init__(self, tasks, *args, **kwargs):
        ''' '''
        super().__init__(*args, **kwargs)
        self.fields['task'].queryset = tasks

tasks/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from django.contrib.auth.mixins import LoginRequiredMixin
from tasks import models, forms
from houses.models import House
from utils import views as uviews


class TasksList(uviews.HasHouseMixin, ListView):
    ''' '''

    context_object_name = 'tasks'
    model = models.Task
    template_name = 'tasks/list.html'

    def get_queryset(self):
        ''' '''
        return self.model.objects.get_for_user(self.request.user)


class TaskDetails(LoginRequiredMixin, uviews.ObjectAccessReadMixin, DetailView):
    ''' '''

    model = models.Task
    context_object_name = 'task'
    template_name = 'tasks/details.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        ''' '''
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['user_rate'] = models.TaskRate.objects.filter(user=self.request.user).first()
        return context


class TaskSaveMixin():
    ''' '''

    model = models.Task
    template_name = 'tasks/form.html'
    form_class = forms.TaskForm

    def get_form_kwargs(self):
        ''' '''
        kwargs = super().get_form_kwargs()
        kwargs.update({'houses': House.objects.get_for_user(self.request.user)})
        return kwargs


class TaskAdd(uviews.HasHouseMixin, TaskSaveMixin, uviews.AddUserMixin, CreateView):
    ''' '''

    success_url = reverse_lazy('tasks:list')


class TaskUpdate(uviews.IsOwnerMixin, TaskSaveMixin, UpdateView):
    ''' '''

    def get_success_url(self):
        ''' '''
        return reverse('tasks:details', args=(self.object.id,))


@method_decorator(require_POST, name='dispatch')
class TaskDelete(uviews.IsOwnerMixin, DeleteView):
    ''' '''

    model = models.Task
    success_url = reverse_lazy('tasks:list')


class TaskRelationsMixin():
    ''' '''

    def get_success_url(self):
        ''' '''
        return reverse('tasks:details', args=(self.object.task_id,))

    def get_form_kwargs(self):
        ''' '''
        kwargs = super().get_form_kwargs()
        kwargs.update({'tasks': models.Task.objects.get_for_user(self.request.user)})
        return kwargs


class TaskRateSaveMixin(TaskRelationsMixin):
    ''' '''

    model = models.TaskRate
    form_class = forms.TaskRateForm


@method_decorator(require_POST, name='dispatch')
class TaskRateAdd(uviews.HasHouseMixin, uviews.AddUserMixin, TaskRateSaveMixin, CreateView):
    ''' '''


@method_decorator(require_POST, name='dispatch')
class TaskRateUpdate(uviews.IsOwnerMixin, TaskRateSaveMixin, UpdateView):
    ''' '''


@method_decorator(require_POST, name='dispatch')
class TaskMessageAdd(uviews.HasHouseMixin, uviews.AddUserMixin, TaskRelationsMixin, CreateView):
    ''' '''

    model = models.TaskMessage
    form_class = forms.TaskMessageForm

tasks/templates/tasks/details.html
{% extends "base.html" %}
{% load custom %}

{% block title %}{{ block.super }} Задачи{% endblock title %}

{% block content %}

<div class="row">
  <div class="row">
    <div class="col">
      <h2>{{ task.title }}</h2>
    </div>
    {% if task.user == user %}
      {% url 'tasks:update' task.id as update_url %}
      {% url 'tasks:delete' task.id as delete_url %}
      {% include "utils/actions.html" with update_url=update_url delete_url=delete_url %}
    {% endif %}
  </div>
  <div class="row mb-3">
    <div class="col-sm-4">
      Важность/Проголосовали: {{ task.rate|default_if_none:0 }}/{{ task.rated|default_if_none:0 }}
    </div>
  </div>
  <div class="row mb-3">
    <div class="col">{{ task.description }}</div>
  </div>
</div>

<div class="row mt-1">
  <div class="col border">
    <form method="POST" action="{% if user_rate %}{% url 'tasks:rate-update' user_rate.id %}{% else %}{% url 'tasks:rate-add' %}{% endif %}">
      {% csrf_token %}
      <input type="hidden" name="task" value="{{ task.id }}">
      <div class="row">
        <div class="col pt-3">
          <label for="rate" class="form-label">Оцените важность задачи:</label>
          {% for val in '12345'|make_list %}
            <div class="form-check form-check-inline">
              <input class="form-check-input" type="radio" name="rate" id="rate{{ val }}" value="{{ val }}" {% if user_rate.rate|stringformat:'1d' == val %}checked=""{% endif %}>
              <label class="form-check-label" for="rate{{ val }}">{{ val }}</label>
            </div>
          {% endfor %}
        </div>
        <div class="col-sm-2 mt-1 ms-auto">
          <button class="w-100 btn btn-primary btn-md" type="submit">Сохранить</button>
        </div>
      </div>
    </form>
  </div>
  <div class="col-sm-4 pt-1">
    <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapse" role="button" aria-expanded="false" aria-controls="collapseExample">
      Поучаствовать в обсуждении
    </a>
  </div>
</div>

<div class="collapse row border mt-1" id="collapse">
  <div class="col">
    <form method="POST" action="{% url 'tasks:message-add' %}">
      {% csrf_token %}
      <input type="hidden" name="task" value="{{ task.id }}">
      <div class="row">
        <div class="col">
          <label for="message" class="form-label">Сообщение</label>
          <textarea id="message" name="message" class="form-control" rows="5"></textarea>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-2 mt-1 ms-auto">
          <button class="w-100 btn btn-primary btn-lg" type="submit">Сохранить</button>
        </div>
      </div>
    </form>
  </div>
</div>

{% if task.messages.count %}
<div class="row mt-5">
  <div class="col">
    <h3>Обсуждение</h3>
    {% for message in task.messages.all %}
      <div class="card">
        <div class="card-body">
          <div class="card-title">
            Сообщение от: <b>{{ message.user.title }}</b>, {{ message.created_dt|change_tz:user|date:'d.m.Y H:i:s' }}
          </div>
          <p class="card-text">{{ message.message }}</p>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
{% endif %}

{% endblock content %}

tasks/templates/tasks/form.html
{% extends "base.html" %}

{% block title %}{{ block.super }} Задачи{% endblock title %}

{% block content %}

<div class="col-lg-6">

  <form method="POST" class="needs-validation" novalidate>
    {% csrf_token %}
    <div class="row g-3">

      <div class="col-12">
        <label for="title" class="form-label">Название</label>
        <input type="text" id="title" name="title" class="form-control {% if form.is_bound %}is-{% if form.title.errors %}in{% endif %}valid{% endif %}" required autofocus value="{{ form.title.value|default_if_none:'' }}">
        <div class="invalid-feedback">{{ form.title.errors }}</div>
      </div>

      <div class="col-12">
        <label for="message" class="form-label">Описание</label>
        <textarea id="message" name="description" class="form-control" rows="5">{{ form.description.value }}</textarea>
      </div>

      <div class="col-12">
        <label for="house" class="form-label">Дом</label>
        <select id="house" class="form-select" name="house">
          {% if form.house|length == 2 %}
            {{ form.house.1 }}
          {% else %}
            {% for option in form.house %}
              {{ option }}
            {% endfor %}
          {% endif %}
        </select>
        <div class="invalid-feedback">{{ form.house.errors }}</div>
      </div>

      <hr class="my-4"/>

      <div class="col-12">
        <button class="w-100 btn btn-primary btn-lg" type="submit">Сохранить</button>
      </div>

    </div>
  </form>
</div>

{% endblock content %}

tasks/templates/tasks/list-item.html
<div class="card">
  <div class="card-body">
    <div class="card-title">
      <div class="row">
        <div class="col-md-5 fs-3">{{ task.title }}</div>
        {% if task.user == user %}
            {% url 'tasks:update' task.id as update_url %}
            {% url 'tasks:delete' task.id as delete_url %}
            {% include "utils/actions.html" with update_url=update_url delete_url=delete_url %}
        {% endif %}
      </div>
    </div>
    <p class="card-text">Важность/Проголосовали: {{ task.rate|default_if_none:0 }}/{{ task.rated|default_if_none:0 }}</p>
    <a href="{% url 'tasks:details' task.id %}">Подробнее</a>
  </div>
</div>

tasks/templates/tasks/list.html
{% extends "base.html" %}

{% block title %}{{ block.super }} Задачи{% endblock title %}

{% block content %}

  {% regroup tasks by house as groupped_tasks %}

  {% if groupped_tasks|length > 1 %}
	<ul class="nav nav-tabs" role="tablist" id="tabsNav">
	  {% for tsk in groupped_tasks %}
	    <li class="nav-item">
	      <a class="nav-link {% if forloop.counter0 == 0 %}active{% endif %}" id="tab-{{ tsk.grouper.id }}" aria-current="page" href="#">{{ tsk.grouper.title }}</a>
	    </li>
	  {% endfor %}
	</ul>
	<div class="tab-content" id="tasksTabs">
	  {% for tsk in groupped_tasks %}
	    <div class="tab-pane fade show {% if forloop.counter0 == 0 %}active{% endif %}" id="{{ tsk.grouper.id }}" role="tabpanel" aria-labelledby="tab-{{ tsk.grouper.id }}">
          {% for task in tsk.list %}
            {% include 'tasks/list-item.html' with task=task %}
          {% endfor %}
	    </div>
	  {% endfor %}
	</div>
  {% else %}
    {% for task in tasks %}
      {% include 'tasks/list-item.html' with task=task %}
    {% endfor %}
  {% endif %}

{% endblock content %}