forum/urls.py
from django.urls import path
from forum import views


app_name = 'forum'
urlpatterns = [
    path('', views.CategoriesList.as_view(), name='list'),
    path('<int:pk>/', views.CategoryDetails.as_view(), name='details'),
    path('threads/add/', views.ThreadAdd.as_view(), name='thread-add'),
    path('threads/<int:pk>/', views.ThreadDetails.as_view(), name='thread-details'),
    path('messages/add/', views.MessageAdd.as_view(), name='message-add'),
]

houses/urls.py
from django.urls import path
from houses import views


app_name = 'houses'
urlpatterns = [
    path('', views.HousesList.as_view(), name='list'),
    path('<int:pk>/update-info/', views.HouseInfoUpdate.as_view(), name='update-info'),
    path('unlink/<int:pk>/', views.UnlinkUser.as_view(), name='user-unlink'),
    path('link/', views.link_user, name='user-link'),
]

notices/urls.py
from django.urls import path
from notices import views


app_name = 'notices'
urlpatterns = [
    path('', views.NoticesList.as_view(), name='list'),
    path('add/', views.NoticeAdd.as_view(), name='add'),
    path('<int:pk>/update/', views.NoticeUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', views.NoticeDelete.as_view(), name='delete'),
]

tasks/urls.py
from django.urls import path
from tasks import views


app_name = 'tasks'
urlpatterns = [
    path('', views.TasksList.as_view(), name='list'),
    path('<int:pk>/', views.TaskDetails.as_view(), name='details'),
    path('add/', views.TaskAdd.as_view(), name='add'),
    path('<int:pk>/update/', views.TaskUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', views.TaskDelete.as_view(), name='delete'),
    path('rate/add/', views.TaskRateAdd.as_view(), name='rate-add'),
    path('rate/<int:pk>/update/', views.TaskRateUpdate.as_view(), name='rate-update'),
    path('message/add/', views.TaskMessageAdd.as_view(), name='message-add'),
]

users/urls.py
from django.urls import path
from users import views


app_name = 'users'
urlpatterns = [
    path('details/', views.UserDetails.as_view(), name='details'),
    path('update/', views.UserUpdate.as_view(), name='update'),
    path('register/', views.UserRegister.as_view(), name='register'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>

<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="ТСЖ,ЖКХ,жилищно-коммунальное хозяйство,сайт ТСЖ,товарищество собственников жилья,сайт дома">

<title>
  {% block title %} {{ house_title }} {% endblock title %}
</title>

<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/css.css' %}" rel="stylesheet">
<link rel="icon" href="{% static 'images/favicon.ico' %}">
{% block css %}{% endblock css %}

</head>
<body class="d-flex flex-column h-100">

<div class="container">
  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 text-center">
        <a class="blog-header-logo text-dark" href="{% url 'index' %}">
          {% if house_logo %} 
            <img src="{{ house_logo.url }}"/>
          {% else %}
            <h3>{{ house_title }}</h3>
          {% endif %}
        </a>
      </div>
      <div class="col-2 text-center" id="time"></div>
      <div class="col-4 d-flex justify-content-end align-items-center">
        {% if user.is_authenticated %}
          <a class="btn btn-sm btn-outline-secondary" href="{% url 'users:details' %}">Профиль</a>
          &nbsp;
          <a class="btn btn-sm btn-outline-secondary" href="{% url 'logout' %}">Выйти</a>
        {% else %}
          <a class="btn btn-sm btn-outline-secondary" href="{% url 'login' %}">Войти</a>
          &nbsp;
          <a class="btn btn-sm btn-outline-secondary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
      </div>
    </div>
  </header>
  <div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
      {% if house_registered %}
        <span class="p-2">
          <a href="{% url 'meetings:list' %}">Собрания</a>
          {% if user.is_house_admin %}
            {% url 'meetings:add' as url %}
            {% include 'utils/add.html' with url=url %}
          {% endif %}
        </span>
        <span class="p-2">
          <a href="{% url 'tasks:list' %}">Задачи</a>
          {% url 'tasks:add' as url %}
          {% include 'utils/add.html' with url=url %}
        </span>
        <span class="p-2">
          <a href="{% url 'houses:list' %}">Информация</a>
        </span>
      {% endif %}
      <span class="p-2">
        <a href="{% url 'notices:list' %}">Объявления</a>
        {% if user.is_authenticated %}
          {% url 'notices:add' as url %}
          {% include 'utils/add.html' with url=url %}
        {% endif %}
      </span>
      <span class="p-2">
        <a href="{% url 'documents:list' %}">Документы</a>
        {% if user.is_authenticated and user.is_house_admin %}
          {% url 'documents:add' as url %}
          {% include 'utils/add.html' with url=url %}
        {% endif %}
      </span>
      <span class="p-2">
        <a href="{% url 'companies:list' %}">Упр. компании</a>
        {% if user.is_authenticated and user.is_house_admin %}
          {% url 'companies:add' as url %}
          {% include 'utils/add.html' with url=url %}
        {% endif %}
      </span>
      <span class="p-2">
        <a href="{% url 'workers:list' %}">Мастера</a>
        {% if user.is_authenticated %}
          {% url 'workers:add' as url %}
          {% include 'utils/add.html' with url=url %}
        {% endif %}
      </span>
      <span class="p-2">
        <a href="{% url 'forum:list' %}">Форум</a>
      </span>
    </nav>
  </div>
</div>

<main class="flex-shrink-0">
  <div class="container pt-5">
    {% block content %}{% endblock content %}
  </div>
</main>

<footer class="footer mt-auto py-3 bg-light">
  <div class="container">
    <span class="text-muted">
      По всем вопросам пишите <a href="{% url 'forum:details' 1 %}">сюда</a>
    </span>
    <span class="text-muted ms-5">
      Иконка сайта создана <a href="http://shlyapnikova.deviantart.com" target="_blank">Анной Шляпниковой</a>
    </span>
    <span class="text-muted ms-5">
      На сайте используются файлы cookie
    </span> 
  </div>
</footer>

<script type="text/javascript" src="{% static 'vendor/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/js.js' %}"></script>
{% block js %}{% endblock js %}

</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}

<div class ="row">
  <div class="col">
    

Cupiditate similique est quibusdam officia rerum. Deserunt amet itaque et nihil illum eum in. Dolor excepturi cupiditate odio.

Quidem dolore debitis ad magnam quia rerum quia dolores. Est tenetur mollitia quaerat et. Corrupti omnis quaerat nihil ipsum amet. Et architecto quia voluptatem mollitia et sed est. In odit ea iste optio.

Tenetur autem quo alias repellat sit consequatur sed. Tempora quos ducimus sed itaque repellendus similique aut. Suscipit consequatur eum ipsam neque. Et cumque qui rerum vel optio. Et aut animi odit.

Omnis nobis facere expedita. Deserunt deserunt ab commodi praesentium. Possimus dignissimos veritatis minus sit et ut et rerum.

Tempora ducimus aliquid excepturi ad ullam id asperiores voluptatem. Eum aut delectus ipsum consectetur voluptatibus molestiae. Et ad iure ipsam facilis qui. Esse nam nemo et. Maxime quia perferendis veritatis aspernatur repellat sunt. Asperiores illo voluptatem nesciunt quaerat sed dolorum aut modi.

  </div>
</div>

{% if house_registered %}
<div class="row mt-3">
  <div class="col">
    <div class="row"><h4>Актуальные задачи</h4></div>
    {% for task in tasks %}
      {% include 'tasks/list-item.html' with task=task %}
    {% endfor%}
  </div>
  <div class="col-md-3">
    {% if next_meeting %}
      <div class="row"><h4>Предстоящее собрание:</h4></div>
      <div class="row"><span>{{ next_meeting.appointed_dt|date:'d.m.Y H:i:s' }}</span></div>
      <div class="row"><span>{{ next_meeting.appointed_place }}</span></div>
    {% endif %}
    {% if last_meeting %}
      <div class="row"><h4>Прошедшее собрание:</h4></div>
      <div class="row"><span>{{ last_meeting.appointed_dt|date:'d.m.Y H:i:s' }}</span></div>
      <div class="row"><span>{{ last_meeting.appointed_place }}</span></div>
    {% endif %}
  </div>
</div>
{% endif %}

<div class="row mt-3">
  <div class="row"><h4>Объявления</h4></div>
  {% for notice in notices %}
    {% include 'notices/list-item.html' with notice=notice %}
  {% endfor %}
</div>

{% endblock content %}